export const infos = [
  {
    tag: "Giftcard",
    img: "images/AmazonTag.png",
    alt: "AmazonTag",
    title: "Amazon Gift Card",
    text: "Amazon Gift Card is a global fashion destination for 20-somethings, selling all the freshest styles complemented by exclusive content....",
    icon: "Info",
    fees: "This card has a fee of $ 0.99",
    btnTitle: "Purchase card",
    btnIcon: "Arrow-Right",
  },
  {
    tag: "Giftcard",
    img: "images/AmazonTag.png",
    alt: "AmazonTag",
    title: "Amazon Gift Card",
    text: "Amazon Gift Card is a global fashion destination for 20-somethings, selling all the freshest styles complemented by exclusive content....",
    icon: "Info",
    fees: "This card has a fee of $ 0.99",
    btnTitle: "Purchase card",
    btnIcon: "Arrow-Right",
  },
  {
    tag: "Giftcard",
    img: "images/AmazonTag.png",
    alt: "AmazonTag",
    title: "Amazon Gift Card",
    text: "Amazon Gift Card is a global fashion destination for 20-somethings, selling all the freshest styles complemented by exclusive content....",
    icon: "Info",
    fees: "This card has a fee of $ 0.99",
    btnTitle: "Purchase card",
    btnIcon: "Arrow-Right",
  },
  {
    tag: "Giftcard",
    img: "images/AmazonTag.png",
    alt: "AmazonTag",
    title: "Amazon Gift Card",
    text: "Amazon Gift Card is a global fashion destination for 20-somethings, selling all the freshest styles complemented by exclusive content....",
    icon: "Info",
    fees: "This card has a fee of $ 0.99",
    btnTitle: "Purchase card",
    btnIcon: "Arrow-Right",
  },
];
